project:
  type: website
  output-dir: docs
  
website:
  title: "ARSRL DigiEpi Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: syllabus.qmd
        text: Syllabus  
      - href: speakers.qmd
        text: Resource Speakers
      - href: concept_overview.qmd
        text: Concept Overview
      - text: Module
        menu:
          - module1/module1.qmd
          - module2/module2.qmd
          - module3/module3.qmd
      - text: Workshop Materials
        menu:
          - href: https://forms.gle/MdbHdcAYR5QdEYi97
            text: Pre-test
          - href: https://forms.gle/MdbHdcAYR5QdEYi97
            text: Post-test
          - quick_guide.qmd
          - href: https://drive.google.com/file/d/1rKz3pkomDnZwkpRww6HTpRsTZdBCctYu/view?usp=sharing
            text: Worksheet - SatScan
          - href: https://drive.google.com/file/d/1zNlN7iH8Kju3EclBB9S8FQvdPXw-5Hqj/view?usp=sharing
            text: Worksheet - Epicollect
          - evaluation.qmd
      - href: https://forms.gle/oBJVAtp1y2dhJrTMA
        text: Got a question?
          
    tools:
      - icon: link
        href: https://www.arsp.com.ph
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Antimicrobial Resistance Surveillance Reference Laboratory"

format:
  html:
    theme: vapor
    page-layout: full
    toc: true

editor: source

